version: '3.7' 

services: 
  backend:
    build: 
      context: backend/Magisterka-backend/WebApplication1/
      dockerfile: Dockerfile
    container_name: backend
    environment:
      MyAppDatabase_ConnectionString: "server=database;user=myuser;password=MyP@ssw0rd;database=menadzer;"
      MyApp_Login: "" # your own gmail login
      MyApp_Password: "" # your own gmail password
      MyApp_FrontURL: "http://frontend:80"
    networks:
     - app
    depends_on:
      - database
    networks:
      - app

  database:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "MyP@ssw0rd"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "1433:1433"
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr & sleep 30s \
        && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P MyP@ssw0rd -i /docker-entrypoint-initdb.d/menadzer.sql \
        && tail -f /dev/null
    networks:
      - app


  frontend:
    # image: nginx
    build: 
      context: frontend/magisterka-frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      ADDRESS: frontend
      BACKEND_SERVICE: backend
      PORT: 80
    ports:
     - 80:80
     - 443:443
    networks:
     - app
    command: /bin/sh -c "export BACKEND_SERVICE && export ADDRESS && export PORT && envsubst '$${ADDRESS} $${BACKEND_SERVICE} $${PORT}' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - backend

volumes:
  database-magisterka:
    name: database-magisterka
networks:
  app:
    name: app
    external: true

